 export const countries = [
    { value: 'Argentina', label: 'Argentina', flag: 'https://flagpedia.net/data/flags/icon/72x54/ar.png' },
    { value: 'Bolivia', label: 'Bolivia', flag: 'https://flagpedia.net/data/flags/icon/72x54/bo.png' },
    { value: 'Brasil', label: 'Brasil', flag: 'https://flagpedia.net/data/flags/icon/72x54/br.png' },
    { value: 'Chile', label: 'Chile', flag: 'https://flagpedia.net/data/flags/icon/72x54/cl.png' },
    { value: 'Colombia', label: 'Colombia', flag: 'https://flagpedia.net/data/flags/icon/72x54/co.png' },
    { value: 'Costa rica', label: 'Costa Rica', flag: 'https://flagpedia.net/data/flags/icon/72x54/cr.png' },
    { value: 'Honduras', label: 'Honduras', flag: 'https://flagpedia.net/data/flags/icon/72x54/hn.png' },
    { value: 'Mexico', label: 'Mexico', flag: 'https://flagpedia.net/data/flags/icon/72x54/mx.png' },
    { value: 'Ecuador', label: 'Ecuador', flag: 'https://flagpedia.net/data/flags/icon/72x54/ec.png' },
    { value: 'España', label: 'España', flag: 'https://flagpedia.net/data/flags/icon/72x54/es.png' },
    { value: 'Paraguay', label: 'Paraguay', flag: 'https://flagpedia.net/data/flags/icon/72x54/py.png' },
    { value: 'Uruguay', label: 'Uruguay', flag: 'https://flagpedia.net/data/flags/icon/72x54/uy.png' },
    { value: 'Peru', label: 'Peru', flag: 'https://flagpedia.net/data/flags/icon/72x54/pe.png' },
    { value: 'Nicaragua', label: 'Nicaragua', flag: 'https://flagpedia.net/data/flags/icon/72x54/ni.png' },
    { value: 'Panama', label: 'Panama', flag: 'https://flagpedia.net/data/flags/icon/72x54/pa.png' },
    { value: 'El salvador', label: 'El salvador', flag: 'https://flagpedia.net/data/flags/icon/72x54/sv.png' },
    { value: 'Republica Dominicana', label: 'R. Dominicana ', flag: 'https://flagpedia.net/data/flags/icon/72x54/bo.png' },
    { value: 'Venezuela', label: 'Venezuela', flag: 'https://flagpedia.net/data/flags/icon/72x54/ve.png' },
     
  ];