 export const countries = [
    { value: 'AR', label: 'Argentina', flag: 'https://flagpedia.net/data/flags/icon/72x54/ar.png' },
    { value: 'BO', label: 'Bolivia', flag: 'https://flagpedia.net/data/flags/icon/72x54/bo.png' },
    { value: 'BR', label: 'Brasil', flag: 'https://flagpedia.net/data/flags/icon/72x54/br.png' },
    { value: 'CL', label: 'Chile', flag: 'https://flagpedia.net/data/flags/icon/72x54/cl.png' },
    { value: 'CO', label: 'Colombia', flag: 'https://flagpedia.net/data/flags/icon/72x54/co.png' },
    { value: 'CR', label: 'Costa Rica', flag: 'https://flagpedia.net/data/flags/icon/72x54/cr.png' },
    { value: 'HN', label: 'Honduras', flag: 'https://flagpedia.net/data/flags/icon/72x54/hn.png' },
    { value: 'MX', label: 'Mexico', flag: 'https://flagpedia.net/data/flags/icon/72x54/mx.png' },
    { value: 'EC', label: 'Ecuador', flag: 'https://flagpedia.net/data/flags/icon/72x54/ec.png' },
    { value: 'ES', label: 'España', flag: 'https://flagpedia.net/data/flags/icon/72x54/es.png' },
    { value: 'PY', label: 'Paraguay', flag: 'https://flagpedia.net/data/flags/icon/72x54/py.png' },
    { value: 'UY', label: 'Uruguay', flag: 'https://flagpedia.net/data/flags/icon/72x54/uy.png' },
    { value:'PE', label: 'Peru', flag: 'https://flagpedia.net/data/flags/icon/72x54/pe.png' },
    { value: 'NI', label: 'Nicaragua', flag: 'https://flagpedia.net/data/flags/icon/72x54/ni.png' },
    { value: 'PA', label: 'Panama', flag: 'https://flagpedia.net/data/flags/icon/72x54/pa.png' },
    { value: 'SV', label: 'El salvador', flag: 'https://flagpedia.net/data/flags/icon/72x54/sv.png' },
    { value: 'DO', label: 'R. Dominicana ', flag: 'https://flagpedia.net/data/flags/icon/72x54/bo.png' },
    { value: 'VE', label: 'Venezuela', flag: 'https://flagpedia.net/data/flags/icon/72x54/ve.png' },
     
  ];
